### ISSUE TITLE
How to get banner height dynamically? 

### ISSUE THREAD

**Issue by nikita-bosenko** [jjjuande/EasyGoogleMobileAds#3]
First, thank you for this solution!

I am trying to position all the elements on the page relatively to a banner so it does not cover important parts. But I don't quite get how to get exact height of the banner after it has been loaded and showed. Could you help with that please?

Thank you and sorry for a nooby question.

**Comment by jjjuande** [comment]
The Github issues section isn't for support purposes. Sorry. :(
Ask on https://github.com/playgameservices/play-games-plugin-for-unity (the oficial site)
